# Generated by Django 5.2.7 on 2025-11-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('founded', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'country', 'founded')},
            },
        ),
    ]
